[workspace]
members = [
    "appointment_service",
    "clinic_core",
    "clinic_service",
    "common",
    "doctor_service",
    "patient_service"
]

resolver = "2"

[workspace.dependencies]
actix-web = "4.12.1"
mongodb = "3.4.1"
serde = { version = "1.0", features = ["derive"] }